// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/lesson/:lessonId": {
    params: {
      "lessonId": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/lesson/:lessonId" | "/*";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/lesson.tsx": {
    id: "routes/lesson";
    page: "/lesson/:lessonId";
  };
  "routes/catchall.tsx": {
    id: "routes/catchall";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/lesson": typeof import("./app/routes/lesson.tsx");
  "routes/catchall": typeof import("./app/routes/catchall.tsx");
};